In [1]:
import pandas as pd
from api_keys import AV_api
import requests

In [8]:
import requests

url = 'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol=IBM&apikey=demo'
r = requests.get(url)
data = r.json()

data.keys()

{'fiscalDateEnding': '2023-09-30',
 'reportedCurrency': 'USD',
 'grossProfit': '8023000000',
 'totalRevenue': '14752000000',
 'costOfRevenue': '6729000000',
 'costofGoodsAndServicesSold': '42000000',
 'operatingIncome': '1994000000',
 'sellingGeneralAndAdministrative': '4458000000',
 'researchAndDevelopment': '1685000000',
 'operatingExpenses': '6029000000',
 'investmentIncomeNet': 'None',
 'netInterestIncome': '-412000000',
 'interestIncome': '156000000',
 'interestExpense': '412000000',
 'nonInterestIncome': '265000000',
 'otherNonOperatingIncome': '97000000',
 'depreciation': '521000000',
 'depreciationAndAmortization': '572000000',
 'incomeBeforeTax': '1863000000',
 'incomeTaxExpense': '159000000',
 'interestAndDebtExpense': '412000000',
 'netIncomeFromContinuingOperations': '1714000000',
 'comprehensiveIncomeNetOfTax': '2105000000',
 'ebit': '2275000000',
 'ebitda': '2847000000',
 'netIncome': '1704000000'}

In [11]:
pd.DataFrame(data['quarterlyReports'])

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2023-09-30,USD,8023000000,14752000000,6729000000,42000000,1994000000,4458000000,1685000000,6029000000,...,521000000,572000000,1863000000,159000000,412000000,1714000000,2105000000,2275000000,2847000000,1704000000
1,2023-06-30,USD,8501000000,15475000000,6974000000,61000000,1984000000,4900000000,1687000000,6517000000,...,520000000,557000000,2002000000,419000000,423000000,1581000000,1863000000,2425000000,2982000000,1583000000
2,2023-03-31,USD,7509000000,14252000000,6743000000,30000000,256000000,4853000000,1655000000,7253000000,...,527000000,547000000,1051000000,124000000,367000000,934000000,888000000,1418000000,1965000000,927000000
3,2022-12-31,USD,9632000000,16690000000,7058000000,190000000,3294000000,4766000000,1604000000,6338000000,...,570000000,567000000,3154000000,444000000,313000000,2870000000,3109000000,3467000000,4034000000,2710000000
4,2022-09-30,USD,7430000000,14107000000,6677000000,57000000,1471000000,4391000000,1611000000,5959000000,...,586000000,577000000,-4483000000,-1287000000,295000000,-3214000000,1834000000,-4188000000,-3611000000,-3196000000
5,2022-06-30,USD,8290000000,15535000000,7246000000,120000000,2377000000,4855000000,1673000000,5913000000,...,620000000,626000000,1649000000,257000000,297000000,1465000000,1755000000,1946000000,2572000000,1392000000
6,2022-03-31,USD,7335000000,14197000000,6862000000,19000000,470000000,4597000000,1679000000,6865000000,...,631000000,625000000,694000000,-39000000,311000000,662000000,1436000000,1005000000,1630000000,733000000
7,2021-12-31,USD,9501000000,16694000000,7195000000,89000000,913000000,4903000000,1625000000,5194000000,...,749000000,632000000,2739000000,406000000,303000000,2462000000,5136000000,3042000000,3674000000,2333000000
8,2021-09-30,USD,7106000000,13251000000,6145000000,49000000,1761000000,4306000000,1606000000,6410000000,...,1037000000,647000000,906000000,-224000000,291000000,1037000000,1480000000,1196000000,1843000000,1130000000
9,2021-06-30,USD,7852000000,14218000000,6366000000,103000000,2304000000,4849000000,1641000000,6700000000,...,1050000000,630000000,1426000000,101000000,281000000,810000000,1930000000,1707000000,2337000000,1325000000
10,2021-03-31,USD,7027000000,13187000000,6160000000,59000000,1084000000,4688000000,1616000000,7120000000,...,1052000000,620000000,795000000,-160000000,280000000,403000000,2036000000,1075000000,1695000000,955000000
11,2020-12-31,USD,5813000000,1926000000,-3888000000,181000000,-4000000000,4712000000,1540000000,2000000000,...,1089000000,610000000,884000000,-472000000,317000000,-305000000,603000000,1201000000,1811000000,1356000000
12,2020-09-30,USD,8430000000,17560000000,9130000000,64000000,2358000000,4647000000,1515000000,6072000000,...,1070000000,613000000,1826000000,128000000,323000000,1698000000,1870000000,2149000000,2762000000,1698000000
13,2020-06-30,USD,8700000000,18123000000,9423000000,117000000,2121000000,5248000000,1582000000,6579000000,...,1056000000,623000000,1570000000,209000000,323000000,1362000000,1888000000,1893000000,2516000000,1361000000
14,2020-03-31,USD,7922000000,17571000000,9649000000,76000000,-145000000,5955000000,1625000000,8067000000,...,1012000000,622000000,-51000000,-1226000000,326000000,1176000000,489000000,275000000,897000000,1175000000
15,2019-12-31,USD,6145000000,2344000000,-3801000000,387000000,4048000000,3553000000,1517000000,7052000000,...,1021000000,629000000,3323000000,-347000000,354000000,1380000000,4159000000,3677000000,4306000000,3670000000
16,2019-09-30,USD,8336000000,18028000000,9692000000,75000000,1872000000,5024000000,1553000000,6464000000,...,1058000000,611000000,1521000000,-151000000,432000000,1673000000,1427000000,1953000000,2564000000,1672000000
17,2019-06-30,USD,9010000000,19161000000,10151000000,74000000,1950000000,5456000000,1407000000,7060000000,...,987000000,307000000,2767000000,269000000,348000000,2499000000,2839000000,3115000000,3422000000,2498000000
18,2019-03-31,USD,8043000000,18182000000,10139000000,55000000,1616000000,4691000000,1433000000,6427000000,...,1143000000,303000000,1880000000,289000000,210000000,1593000000,1899000000,2090000000,2393000000,1591000000
19,2018-12-31,USD,10687000000,21761000000,11073000000,11073000000,4306000000,4701000000,1358000000,6381000000,...,790000000,322000000,4432000000,2481000000,193000000,1953000000,282000000,4625000000,4947000000,1951000000

In [14]:
pd.DataFrame(data['quarterlyReports']).columns

Index(['fiscalDateEnding', 'reportedCurrency', 'grossProfit', 'totalRevenue',
       'costOfRevenue', 'costofGoodsAndServicesSold', 'operatingIncome',
       'sellingGeneralAndAdministrative', 'researchAndDevelopment',
       'operatingExpenses', 'investmentIncomeNet', 'netInterestIncome',
       'interestIncome', 'interestExpense', 'nonInterestIncome',
       'otherNonOperatingIncome', 'depreciation',
       'depreciationAndAmortization', 'incomeBeforeTax', 'incomeTaxExpense',
       'interestAndDebtExpense', 'netIncomeFromContinuingOperations',
       'comprehensiveIncomeNetOfTax', 'ebit', 'ebitda', 'netIncome'],
      dtype='object')